[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

